# Generated by Django 4.2.2 on 2024-10-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cart_id_number',
            new_name='card_id_number',
        ),
    ]
